### PR TITLE
Removes create variable and refactors module usage

### PR DESCRIPTION
**Pull request by eemperor**

### CODE REVIEW

**Comment by eemperor** [comment]
Test results

```
PASS
ok      terraform-aws-tardigrade-cloudwatch-metric-alarms/tests 12.463s
[terratest/test]: Completed successfully!
```

**Review by lorengordon — COMMENTED** [review]
looking good. can you go ahead and remove the tests/go.* files though, and update .gitignore with:

```
# terratest packaging
tests/go.*
```

and update the dependabot config to remove the golang config...

**Comment by eemperor** [comment]
@lorengordon Updated per your comments

**Review by lorengordon — APPROVED** [review]
very nice 🚢

**Pull request merged**
